// Share modal
export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';

// Events
export const GET_INDEX_EVENTS = 'GET_EVENTS';
export const GET_INDEX_FEATURED_EVENTS = 'GET_INDEX_FEATURED_EVENTS';
export const GET_MORE_EVENTS = 'GET_MORE_EVENTS';
export const EVENT_ERROR = 'EVENT_ERROR';
export const EVENT_LOADING = 'EVENT_LOADING';
export const FEATURED_LOADING = 'FEATURED_LOADING';
export const SET_PAGE = 'SET_PAGE';
export const GET_EVENT = 'GET_EVENT';

// Alert
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

// Register & Login
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const ACCOUNT_DELETED = 'ACCOUNT_DELETED';

// Profile
export const PROFILE_LOADING = 'PROFILE_LOADING';
export const GET_PROFILE = 'GET_PROFILE';
export const PROFILE_ERROR = 'PROFILE_ERROR';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';

// Catalogue
export const GET_CATALOGUE_EVENTS = 'GET_CATALOGUE';
export const GET_CATALOGUE_IDS = 'GET_CATALOGUE_EVENT_IDS';
export const ADD_TO_CATALOGUE = 'ADD_TO_CATALOGUE';
export const PUSH_TO_CATALOGUE = 'PUSH_TO_CATALOGUE';
export const CATALOGUE_EVENTS_LOADING = 'CATALOGUE_EVENTS_LOADING';
export const CATALOGUE_IDS_LOADING = 'CATALOGUE_IDS_LOADING';
export const DELETE_FROM_CATALOGUE = 'DELETE_FROM_CATALOGUE';
export const CLEAR_CATALOGUE = 'CLEAR_CATALOGUE';
export const CATALOGUE_ERROR = 'CATALOGUE_ERROR';
