export const GET_EVENTS = 'GET_EVENTS';
export const GET_FEATURED = 'GET_FEATURED';
export const EVENT_ERROR = 'EVENT_ERROR';
export const EVENTS_LOADING = 'EVENTS_LOADING';
export const FEATURED_LOADING = 'FEATURED_LOADING';
